### ISSUE TITLE
[Recommendation] Enable Repository Github Discussions

### ISSUE THREAD

**Issue by m0ham3dx** [morphean-sec/Solidity-DevSecOps-Standard#1]
Consider enabling [Github Discussions](https://docs.github.com/en/discussions) for repositories. This way you can consolidate repo related discussions for future reference. FYI Issues are good too, just that Github Discussions are more designed for running conversations.

**Comment by 0xsomnus** [comment]
Great suggestion! I'll work on it so people can contribute better.
